### ISSUE TITLE
Sync a forum with the plugin 

### ISSUE THREAD

**Issue by aman207** [aman207/DonatorExpress#1]
Add all major forums, like MyBB, XenForo, PHBB, etc etc

**Comment by graywolf336** [comment]
I would love to have this.

**Comment by aman207** [comment]
@graywolf336 

I'm working really hard to do this, but I keep running into bugs.

**Comment by graywolf336** [comment]
@aman207 Good luck, I wish you well! :smile:

**Comment by aman207** [comment]
@graywolf336 Thanks :)

Oh do you have a specific forum that you would like? I can give you a beta version, once it is working.

**Comment by graywolf336** [comment]
I use Xenforo.

One other thing you would possibly look at checking out using is https://github.com/HackerFinn/minecraft-web-api, although I'm not too sure it is the best or safe route to go.

**Comment by aman207** [comment]
@graywolf336 Yeah that's probably not the best way to go.

Thanks for the suggestion anyways.

**Comment by FuZeEclipse** [comment]
I could possibly get a xenforo version out :)

**Comment by aman207** [comment]
@FuZeEclipse Thanks anyways, but I got it covered :)

**Comment by aman207** [comment]
Feature done. In testing phase
