### ISSUE TITLE
Purchase points with in-game currency

### ISSUE THREAD

**Issue by extraspicy12** [aman207/DonatorExpress#11]
Give users the ability to convert in-game currency (via Vault) to points based on some user-defined conversion rate.

**Comment by aman207** [comment]
This will be included in update after the one coming up. 

Thanks for your suggestion!

**Comment by extraspicy12** [comment]
Could you also add the ability to purchase tokens with in-game items? For example, 9 emerald blocks = 1 token.

This would allow servers that use a physical economy - instead of a virtual, vault supported economy - to enjoy the benefits of this feature.

**Comment by aman207** [comment]
Hmm. 

I will have to do some thinking. Ill get back to you.

**Comment by graywolf336** [comment]
:+1:
