### ISSUE TITLE
Doesn't send email confirmation

### ISSUE THREAD

**Issue by Howdareyoukitty** [aman207/DonatorExpress#16]
Hello, I recently setup the web portal and plugin and all is working except for when a user registers, it doesn't send the confirmation email that it says it did.

**Comment by Howdareyoukitty** [comment]
Accidentally put this in suggestions lol.

**Comment by HiddenMotives** [comment]
Hi, this is not a web portal bug. Your server simply can't send emails using the PHP mail() function. You are possibly missing a the mail program such as qmail. I suggest you take a look at: http://bit.ly/13HiIdZ
