### ISSUE TITLE
Purchase Ranks with Signs

### ISSUE THREAD

**Issue by Will-Scarlet** [aman207/DonatorExpress#21]
If you could add the capability to allow players to purchase ranks with signs that would be amazing and help my server more then you would know.

Sign Format:
[Purchase Rank]
%Rank Name
Cost(Amount %Currency)

**Comment by aman207** [comment]
In the next update after this coming one, I will be adding better purchase options, like a custom inventory and signs.

**Comment by Will-Scarlet** [comment]
I am anxiously awaiting your release then =)
