### ISSUE TITLE
E-Mailing

### ISSUE THREAD

**Issue by DylanDirlam** [aman207/DonatorExpress#22]
I am currently using a free web hosting site and they charge in order to user the php mail() function. Is it possible to disable this or disable the e-mail confirmation or is this a necessity?

**Comment by HiddenMotives** [comment]
Currently there is no configurable option to toggle email confirmation.

And I really hope that your not with Zymic Hosting... I suggest you move to 000webhost.com they allow the PHP Mail() function. :D

**Comment by DylanDirlam** [comment]
I am, haha.

**Comment by DylanDirlam** [comment]
I have switched over to 000webhost.com and the e-mail is not going out to my e-mail. Everything else seems to be working fine, but the e-mails are not going through to my e-mail. Junk/spam or Inbox.

**Comment by DylanDirlam** [comment]
We bought a real domain now and are able to use the mail() but it still does not work! It says the e-mail has been sent but never arrives. Support says to check the Error Log which only produces this error:

[Wed Sep 11 01:57:03 2013] [error] [client 50.122.176.112] File does not exist: /home/gravity1/public_html/404.shtml, referer: http://www.gravityx.info/upload/thank-you.html
[Wed Sep 11 01:57:03 2013] [error] [client 50.122.176.112] File does not exist: /home/gravity1/public_html/upload/style/reset.css, referer: http://www.gravityx.info/upload/thank-you.html

It also puts it into the database too.

**Comment by HiddenMotives** [comment]
Did you check your Spam/Junk folder?

**Comment by DylanDirlam** [comment]
Yep

**Comment by ghost** [comment]
DONT USE 000webhost. Immediately back up your data and move over to 3owl.com 000webhost will send you an email saying that you did something and that your account is banned. Please buy premium. DONT USE THEM. THEY ARE SCAMMERS. Btw i wouldnt suggest free hosting anyways

**Comment by DylanDirlam** [comment]
We are using the host of our dedicated server now.

**Comment by aman207** [comment]
Was this issue resolved?

**Comment by DylanDirlam** [comment]
No it has not been.

**Comment by HiddenMotives** [comment]
Did the modify any of the files? And you mentioned you moved to a dedicated server, does that server have all the functions installed and enabled? Such as phpmail();
