### ISSUE TITLE
Error. with db connection.

### ISSUE THREAD

**Issue by ghost** [aman207/DonatorExpress#23]
Is there any ports i need to open on my host for it to work? I am using cpanel. I have opened outside connections to the ip
174.138.160.234
AND e-scape.us
BOTH dont work.

db-username: 'just1end_escape'
db-password: '-------------'
db-host: 'localhost:3306'
db-name: 'just1end_donator'

i've replaced my password with ------------

When i type /donate buy general
I get an error saying hmmm.... blah blah blah couldnt connect to db -- call and admin

Now this is the error log: 

14.09 18:54:00 [Multicraft] Skipped 18 lines due to rate limit (60/s)
14.09 18:53:52 [Server] SEVERE java.lang.NullPointerException
14.09 18:53:52 [Server] SEVERE Error while trying to connect to the database.
14.09 18:53:52 [Server] SEVERE ... 32 more
14.09 18:53:52 [Server] SEVERE at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:292)
14.09 18:53:52 [Server] SEVERE at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:254)
14.09 18:53:52 [Server] SEVERE at java.net.Socket.<init>(Unknown Source)
14.09 18:53:52 [Server] SEVERE at java.net.Socket.<init>(Unknown Source)
14.09 18:53:52 [Server] SEVERE at java.net.Socket.connect(Unknown Source)
14.09 18:53:52 [Server] SEVERE at java.net.Socket.connect(Unknown Source)
14.09 18:53:52 [Server] SEVERE at java.net.SocksSocketImpl.connect(Unknown Source)
14.09 18:53:52 [Server] SEVERE at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
14.09 18:53:52 [Server] SEVERE at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
14.09 18:53:52 [Server] SEVERE at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
14.09 18:53:52 [Server] SEVERE at java.net.PlainSocketImpl.socketConnect(Native Method)
14.09 18:53:52 [Server] SEVERE Caused by: java.net.ConnectException: Connection refused
14.09 18:53:52 [Server] SEVERE at net.minecraft.server.v1_6_R2.ThreadServerApplication.run(SourceFile:582)
14.09 18:53:52 [Server] SEVERE at net.minecraft.server.v1_6_R2.MinecraftServer.run(MinecraftServer.java:419)
14.09 18:53:52 [Server] SEVERE at net.minecraft.server.v1_6_R2.MinecraftServer.s(MinecraftServer.java:486)
14.09 18:53:52 [Server] SEVERE at net.minecraft.server.v1_6_R2.DedicatedServer.t(DedicatedServer.java:226)
14.09 18:53:52 [Server] SEVERE at net.minecraft.server.v1_6_R2.MinecraftServer.t(MinecraftServer.java:590)
14.09 18:53:52 [Server] SEVERE at net.minecraft.server.v1_6_R2.DedicatedServerConnection.b(SourceFile:30)
14.09 18:53:52 [Server] SEVERE at net.minecraft.server.v1_6_R2.ServerConnection.b(SourceFile:37)
14.09 18:53:52 [Server] SEVERE at net.minecraft.server.v1_6_R2.PlayerConnection.e(PlayerConnection.java:116)
14.09 18:53:52 [Server] SEVERE at net.minecraft.server.v1_6_R2.NetworkManager.b(NetworkManager.java:296)
14.09 18:53:52 [Server] SEVERE at net.minecraft.server.v1_6_R2.Packet3Chat.handle(SourceFile:49)
14.09 18:53:52 [Server] SEVERE at net.minecraft.server.v1_6_R2.PlayerConnection.a(PlayerConnection.java:829)
14.09 18:53:52 [Server] SEVERE at net.minecraft.server.v1_6_R2.PlayerConnection.chat(PlayerConnection.java:872)
14.09 18:53:52 [Server] SEVERE at net.minecraft.server.v1_6_R2.PlayerConnection.handleCommand(PlayerConnection.java:954)
14.09 18:53:52 [Server] SEVERE at org.bukkit.craftbukkit.v1_6_R2.CraftServer.dispatchCommand(CraftServer.java:523)
14.09 18:53:52 [Server] SEVERE at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:192)
14.09 18:53:52 [Server] SEVERE at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
14.09 18:53:52 [Server] SEVERE at net.targetcraft.donatorexpress.CommandListener.onCommand(CommandListener.java:759)
14.09 18:53:52 [Server] SEVERE at net.targetcraft.donatorexpress.CommandListener.connectToDatabase(CommandListener.java:106)
14.09 18:53:52 [Server] SEVERE at java.sql.DriverManager.getConnection(Unknown Source)
14.09 18:53:52 [Server] SEVERE at java.sql.DriverManager.getConnection(Unknown Source)
14.09 18:53:52 [Server] SEVERE at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
14.09 18:53:52 [Server] SEVERE at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378)
14.09 18:53:52 [Server] SEVERE at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
14.09 18:53:52 [Server] SEVERE at java.lang.reflect.Constructor.newInstance(Unknown Source)
14.09 18:53:52 [Server] SEVERE at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
14.09 18:53:52 [Server] SEVERE at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
14.09 18:53:52 [Server] SEVERE at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
14.09 18:53:52 [Server] SEVERE at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
14.09 18:53:52 [Server] SEVERE at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
14.09 18:53:52 [Server] SEVERE at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2163)
14.09 18:53:52 [Server] SEVERE at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2371)
14.09 18:53:52 [Server] SEVERE at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2334)
14.09 18:53:52 [Server] SEVERE at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:343)
14.09 18:53:52 [Server] SEVERE at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1116)
14.09 18:53:52 [Server] SEVERE at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
14.09 18:53:52 [Server] SEVERE at java.lang.reflect.Constructor.newInstance(Unknown Source)
14.09 18:53:52 [Server] SEVERE at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
14.09 18:53:52 [Server] SEVERE at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
14.09 18:53:52 [Server] SEVERE at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
14.09 18:53:52 [Server] INFO The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
14.09 18:53:52 [Server] SEVERE com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
14.09 18:53:52 [Server] SEVERE Error while trying to connect to the database

So i ask again any ports? any suggestions? Please Help! skype me at max.mastalerz.

**Comment by aman207** [comment]
Your host should not be localhost. 

Try using 'e-scape.us:3306'

**Comment by aman207** [comment]
BTW what version are you using?

**Comment by ghost** [comment]
okay currently the multicraft is somehow down. I will try what u say tommorow. And if u mean version... web hosting has php it has the 2 newest ones. Webhosting works fine. Just the plugin.
I will come bac when its fixed or i still have issues with it

**Comment by aman207** [comment]
By version I mean when you type /donate about, what version comes up?

**Comment by ghost** [comment]
I fixed it! I hooked up the db to my websites ip not the servers. Occasionally /donate buy general with prompt an error

**Comment by aman207** [comment]
Wow your host sucks then

**Comment by ghost** [comment]
the plugin. Repeat the commands twice

Date: Sun, 15 Sep 2013 19:03:02 -0700

**Comment by aman207** [comment]
It repeats the commands twice?

**Comment by ghost** [comment]
no, the plugin doesnt repeat commands twice but when i type the command the first time it fails the db connection. I have to type it again for it to work. I'll send you an error later

**Comment by aman207** [comment]
This is going to be resolved in version 1.5.1

See issue #26
