### ISSUE TITLE
Error: The server could not create this image.

### ISSUE THREAD

**Issue by michalet** [aman207/DonatorExpress#24]
As the title says, I get this for all four package images.
I'm rather a newbie with apache/php, but will try to get any needed info.

**Comment by xvenom1291x** [comment]
I am receiving the same error. Was looking at the php files and everything looked correct. Unless I overlooked something.....Any solutions?

**Comment by aman207** [comment]
Try to install Imagick on your web server or contact your web host.

**Comment by HiddenMotives** [comment]
Method 1)

Edit /generate/diamond.php and try including the FULL/ABSOLUTE path for the SHOWG.TTF font file.

Example for cPanel Servers:
Find: "$font_file = 'SHOWG.TTF';" in diamond.php and then
Edit it to something like: "$font_file = '/home/cpanelusr/public_html/donate/generate/SHOWG.TTF';" 
Where the "cpanelusr" is the username for the cPanel account and "donate" is the installation directory of the portal.

Method 2)

Edit login-home.php and find the following lines:

```
<img src="generate/diamond.php?text=<?php echo $diamond1; ?>">
<img src="generate/diamond.php?text=<?php echo $diamond2; ?>">
<img src="generate/diamond.php?text=<?php echo $diamond3; ?>">
<img src="generate/diamond.php?text=<?php echo $diamond4; ?>">
```

Replace them with:

```
<img src="http://targetcraft.net/demo/dep/generate/diamond.php?text=<?php echo $diamond1; ?>">
<img src="http://targetcraft.net/demo/dep/generate/diamond.php?text=<?php echo $diamond2; ?>">
<img src="http://targetcraft.net/demo/dep/generate/diamond.php?text=<?php echo $diamond3; ?>">
<img src="http://targetcraft.net/demo/dep/generate/diamond.php?text=<?php echo $diamond4; ?>">
```

What this will do is generate the image from our web server which is running the demo portal efficiently resolving your problems!

**Comment by graywolf336** [comment]
Method one worked for me, thanks.

**Comment by michalet** [comment]
First one worked for me as well, thank you.
