### ISSUE TITLE
Multiple bugs:

### ISSUE THREAD

**Issue by Secretchaos** [aman207/DonatorExpress#27]
Hey man,

First of all keep up the good work!
I really like you plugin and how it is possible to use te same "currency" for multiple servers!

Let me explain the situation:

i got 4 packages

iron
gold
diamond
emerald

they all are one time purchases

Bug 1:

When i do /donate upgrade after i bought iron i can buy the upgrade to but it does not save gold in the userdata as the current package.

Bug 2:

So when i do /donate upgrade again i am buying gold again which i can but it is a one time purchase.  

Bug 3: the commands that i connect to the package: /manuadd & /bc is always runned twice.

Bug 4: whenever the plugin has not run in a while the first /donate buy [package] command fails with a db error (sorry thats all info i got about this)

Hope i gave enough info and if i made a typo don't hate me haha my native language is not english.

Hope you can fix it easily,

Secretchaos

**Comment by aman207** [comment]
For bug number 3, if you happen to add a third command, is it run three times?

I think I know whats wrong with the other bugs. 

I am tied up with fixing bug number 4 right now so sorry if I don't get to the others as quick as I should

**Comment by Secretchaos** [comment]
Strange after i added a third command the bug was gone, and when i readded it to 2 commands it was also gone strange

**Comment by aman207** [comment]
Oh good that's a relief. It was a bug before and I was worried that I didn't fix it.

**Comment by Secretchaos** [comment]
lol it's strange that it sometimes happens? or do you know the problem?

**Comment by aman207** [comment]
I have no idea why it happens sometimes. My guess is because of bug number 4, it tried to reconnect thus sending the commands twice. But all that should be fixed soon. Thanks for letting me know about 1 and 2

**Comment by Secretchaos** [comment]
Yeah man no problem! If you need something tested out just let me know. I think this plugin is just awesome!

**Comment by aman207** [comment]
Yes I think so too XD

**Comment by aman207** [comment]
https://www.dropbox.com/s/4hy7q3dx7ge4xpp/DonatorExpress.jar

This fixes the database problem. Ill start working on 1 and 2 now.

**Comment by aman207** [comment]
https://www.dropbox.com/s/4hy7q3dx7ge4xpp/DonatorExpress.jar

Try this
