### ISSUE TITLE
Images Not Showing on Web Portal

### ISSUE THREAD

**Issue by graywolf336** [aman207/DonatorExpress#3]
Just setup a new instance of the plugin on our test server to test this all out and everything is going good so far, except the portal has no images whatsoever. :cry: Here's a link to our test environment, we haven't tested out or setup the PayPal on here since we just got started. I can give you any information you need, just let me know..and if this has been fixed, more power to ya..where do I find it?

**Comment by HiddenMotives** [comment]
Hi,

I think you forgot to post the link? Could you please post it so I can further analyze the situation?
Also this is Donator Express Version 1.1 Correct?

What control panel and PHP version are you using?

Thanks.

**Comment by graywolf336** [comment]
Sorry about that, the link is http://testing.craftyn.com/donations/. We are using the latest version which is on BukkitDev, according to the plugin it is version 0.6.

Our php version is 5.3.3

**Comment by HiddenMotives** [comment]
You currently are still on version 1.0 = http://testing.craftyn.com/donations/readme.txt
Here is the link to version 1.1 = http://dev.bukkit.org/bukkit-plugins/donator-express/files/6-donator-express-v1-1/

Let me know once you have applied the patch ;)

**Comment by graywolf336** [comment]
Was actually in the middle of posting that when I got the email you replied, will try it out.

**Comment by graywolf336** [comment]
Thanks, it is fixed. :smile:
