### ISSUE TITLE
Players are able to "dupe/steal a rank"

### ISSUE THREAD

**Issue by Secretchaos** [aman207/DonatorExpress#30]
Hi aman207 i found a new bug! 
A dupe/glitch:

If some does donate buy <package>

and a other user uses the command /donate confirm before the donator does

the package goes to the other user! 

this is a serieus problem!

even users without a donator express acount gets the package and no coins are taken!

**Comment by aman207** [comment]
OK thanks for letting me know. I will get working on a fix right away.
