### ISSUE TITLE
Make the Prefix Configurable

### ISSUE THREAD

**Issue by graywolf336** [aman207/DonatorExpress#4]
Besides Issue #3, we are loving the plugin so far. One thing that we would love to have the ability to do is change the prefix that is sent to players via the config. Right now it is a long line of "DonatorExpress" and after doing several commands it can get somewhat spammy. This is more of an enhancement request than a issue.

Thanks again for the plugin.

**Comment by aman207** [comment]
Will do.

**Comment by graywolf336** [comment]
Thanks. :smile:

**Comment by aman207** [comment]
Feature done.
