### ISSUE TITLE
Unable To Purchase Package Unless

### ISSUE THREAD

**Issue by graywolf336** [aman207/DonatorExpress#5]
During our testing we found that we was unable to purchase a package when we had exactly the amount required for that package. So, for our example we have a package titled vip and it cost us five tokens to purchase it. We give our test subject five tokens, he types the command `/donate buy vip` and gets the message saying that he doesn't have enough tokens to purchase it. We then give our test subject one more token, making his total to six, and he types in the command again and he is able purchase that package. We are running the latest version on BukkitDev, 0.6.

I hope that makes sense.

**Comment by aman207** [comment]
Oh nuts.
I will have this fixed asap. 

Bit of an embarasing bug :eek:

**Comment by aman207** [comment]
Fixed. 

https://www.dropbox.com/s/6yaxmndy1t4gfv5/DonatorExpress.zip

**Comment by graywolf336** [comment]
Will try it out tonight, thanks.

If you need/want a CI Jenkins server, I have one which I use that you can use.

**Comment by aman207** [comment]
If you don't mind, sure. 

I was thinking about getting one but I figured I didn't really have a need for it.
