### ISSUE TITLE
No description for packages

### ISSUE THREAD

**Issue by kazeen** [aman207/DonatorExpress#6]
Hi, 
Currently testing this plugin with graywolf.

Anyways we found that the packages do not have a description. 
Not sure if this is a feature that you are working on or not.

Thanks for the plugin.

**Comment by HiddenMotives** [comment]
This could/may be implemented into the plugin, which allows users to view description of the package by typing /donate info (package)

And Admins can set the description of the package by typing /donate setinfo (package) (description)

Thanks for the suggestion!

**Comment by graywolf336** [comment]
Forgot about this one, thanks for doing it for me @kazeen. :+1:

**Comment by aman207** [comment]
Feature done. In testing phase
