### ISSUE TITLE
Images Don't Generate

### ISSUE THREAD

**Issue by graywolf336** [aman207/DonatorExpress#7]
Alrighty, hopefully one last issue before I go as I feel like I'm spamming you. We updated the portal and got that all work, yippe, but we came across an error of which I can't figure out. I'm assuming it is because the portal thinks we don't have GD but [phpinfo()](http://testing.craftyn.com/donations/phpinfo.php) on our server says other wise.

Am I missing something or using the wrong version?

**Comment by HiddenMotives** [comment]
The web portal is working perfectly fine there most likely is a problem with the web server that you currently are running the script on. You can try re-installing php gd, or can try moving the portal to another server and testing to see how it works?
