### ISSUE TITLE
/donate addvc <player> 10 gives error ?1?

### ISSUE THREAD

**Issue by Hekcraft** [aman207/DonatorExpress#8]
> donate addvc zgn 10
> 00:15:56 [WARNING] Unexpected exception while parsing console command "donate addvc zgn 10"
> org.bukkit.command.CommandException: Unhandled exception executing command 'donate' in plugin Donato
> rExpress v0.6.1
>         at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
>         at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:189)
>         at org.bukkit.craftbukkit.v1_6_R2.CraftServer.dispatchCommand(CraftServer.java:523)
>         at org.bukkit.craftbukkit.v1_6_R2.CraftServer.dispatchServerCommand(CraftServer.java:512)
>         at net.minecraft.server.v1_6_R2.DedicatedServer.ar(DedicatedServer.java:262)
>         at net.minecraft.server.v1_6_R2.DedicatedServer.t(DedicatedServer.java:227)
>         at net.minecraft.server.v1_6_R2.MinecraftServer.s(MinecraftServer.java:486)
>         at net.minecraft.server.v1_6_R2.MinecraftServer.run(MinecraftServer.java:419)
>         at net.minecraft.server.v1_6_R2.ThreadServerApplication.run(SourceFile:582)
> Caused by: java.lang.NullPointerException
>         at net.targetcraft.donatorexpress.CommandListener.onCommand(CommandListener.java:295)
>         at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
>         ... 8 more

Running:
http://dl.bukkit.org/downloads/craftbukkit/view/02213_1.6.2-R0.1/

Portal:
http://donations.hekcraft.com

keep up the good work

**Comment by aman207** [comment]
This looks like you have not setup your config properly. It is having a hard time connecting to the database.

**Comment by HiddenMotives** [comment]
Also for the /donate addvc command you need to enter in the players full Minecraft Username.

Example giving myself 10 Tokens I would use: /donate addvc AzroWear 10

**Comment by Hekcraft** [comment]
hi both, thanks for your help, i will have a look at the database issue and report back, as i execute the command correctly wicked plugin and support guys, thanks reassures me, while i got you both, when do you think roughly v2 will come for portal end, or do we just modify these yourself, well just you know what i mean :D once again thank i will be back shortly

**Comment by Hekcraft** [comment]
I believe aman207 was correct, i was trying to connect remotely to  mysql db and connection did not allow this, they are fixing it currently in datacenter,  i will update ticket as soon as possible, thanks guys

**Comment by aman207** [comment]
Glad we could help.  
P.S Ill be adding better error handling next update ;)
